---
  - name: manjaro_setup
    hosts: localhost
    become: yes
    gather_facts: yes
    serial: 1
    tasks:

      - name: Install stuffs
        pacman: pkg={{ item }}
        with_items:
          - yay
          - i3-gaps
          - i3status
          - i3blocks
          - dmenu
          - zsh
          - rxvt-unicode
          - vim
          - neovim
          - unclutter
          - firefox
          - zathura
          - discord
          - ttf-caladea 
          - ttf-carlito
          - ttf-dejavu
          - ttf-liberation
          - ttf-linux-libertine-g
          - noto-fonts
          - adobe-source-code-pro-fonts
          - adobe-source-sans-pro-fonts
          - adobe-source-serif-pro-fonts
          - libreoffice-still
          - steam
          - python-gpgme
          - jack2
          - pulseaudio-jack
          - cadence
          - guitarix
          - freecad
          - kicad
          - lutris
          - xorg-server
          - xorg-xinit
          - autorandr
          - feh
          - patch
          - arduino
          - bluez-utils


      - name: Install dotfiles
        ansible.builtin.shell:
          cmd: cd /home/kp/dotfiles && sh /home/kp/setup.sh
          
      - name: Setup audio group
        ansible.builtin.shell: |
          sudo groupadd audio
          sudo usermod -a -G audio $USER
          sudo ehco "" >> /etc/security/limits.conf
          sudo ehco "# audio group" >> /etc/security/limits.conf
          sudo ehco "@audio - rtprio 95" >> /etc/security/limits.conf
          sudo ehco "@audio - memlock unlimited" >> /etc/security/limits.conf

      - name: Add user to uucp group for arduino serial
        ansible.builtin.shell:
          cmd: sudo usermod -a -G uucp kp



          # TODO
          # echo "blacklist pcspkr" | sudo tee /etc/modprobe.d/nobeep.conf 
          # zsh-autosuggestions git clone
          # zsh-syntax-highlighting git clone
          # vim plug
          # heroic store aur
          # dropbox-cli aur
          # calibre aur
          # prusa-slicer aur
          # wine-stable aur
          # bluez-rfcomm aur
